# Generated by Django 3.1.6 on 2021-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
        migrations.AddField(
            model_name='note',
            name='option1',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='option2',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='option3',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='question',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
